version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      - wp-volume:/var/www/
    restart: always

  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
    container_name: mariadb
    networks:
      - inception
    volumes:
      - db-volume:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
    restart: always

  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        WP_TITLE: ${WP_TITLE}
        WP_TABLE_PREFIX: ${WP_TABLE_PREFIX}
        WP_ADMIN_USER: ${WP_ADMIN_USER}
        WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
    container_name: wordpress
    depends_on:
      - mariadb
    secrets:
      - credentials
      - db_password
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - WP_TITLE=${WP_TITLE}
      - WP_TABLE_PREFIX=${WP_TABLE_PREFIX}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
    restart: always

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: ${WP_VOLUME_PATH}

  db-volume:
    driver_opts:
      o: bind
      type: none
      device: ${DB_VOLUME_PATH}

networks:
  inception:
    driver: bridge

secrets:
  # CHANGE: Corrected paths from ./secrets/ to ../secrets/ to point to ~/incept/secrets/
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  credentials:
    file: ../secrets/credentials.txt
